# Application Name
spring.application.name=order-payment-system

# Server Port (change if 8080 is already used)
server.port=8081

# Logging Level
logging.level.org.springframework=INFO

# Show SQL queries in console (optional)
spring.jpa.show-sql=true

# Format SQL output
spring.jpa.properties.hibernate.format_sql=true

# Hibernate DDL auto (not required if no database)
spring.jpa.hibernate.ddl-auto=update

# Allow bean overriding (optional for simple projects)
spring.main.allow-bean-definition-overriding=true